name: AWS CDK Deploy

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/aws-cdk.yml"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::316516756945:role/github-ci

      - name: CDK Deploy
        working-directory: ./server
        run: npx cdk deploy --all --require-approval never
